### ISSUE TITLE
Can BTM be used to assign topics to new sentences?

### ISSUE THREAD

**Issue by AkshatM** [xiaohuiyan/BTM#1]
Hi,

We're working on short text topic modelling at [DataWeave](http://dataweave.in/), and are interested in using bi-term topic modelling to try to scalably assign products to product titles sourced from e-commerce websites.

We are interested in using your library for this purpose, but so far this library only seems to be able to assign topics to sentences in its training set. 

Is there a way to be able to segment training and prediction into two separate tasks i.e. where we could train on a subset of documents, and attempt to predict another subset? 

Failing that, if training on all new documents is necessary, would BTM be scalable i.e. would it repeat training over all documents, or cache an existing training model and then update the training model with the new document?

Thank you.

**Comment by xiaohuiyan** [comment]
Dear Mahajan:

Thanks for your interest of our work.

There is no barrier for BTM to infer the topics in another subset of
documents. The only thing you need to care is to filter out the words out
of the vocabulary of the training set.

If you new document set is very large, you can scalable BTM with spark. Or
if your just want update the model incrementally, you can use the online
BTM: https://github.com/xiaohuiyan/OnlineBTM. The algorithms is described
on the paper: http://shortext.org/paper/BTM-TKDE.pdf

Bests,
Xiaohui

2015-06-26 12:50 GMT+08:00 Akshat Mahajan notifications@github.com:
