### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jwijffels** [xiaohuiyan/BTM#18]
Under which License is this project distributed?

**Comment by xiaohuiyan** [comment]
BSD-licensed

2018-03-08 5:23 GMT+08:00 jwijffels <notifications@github.com>:

**Comment by jwijffels** [comment]
Thank you for the information. Would it be possible to add that license to the repository?

**Comment by jwijffels** [comment]
I wouldn't mind creating an R wrapper around this code, but for this, can you please add the license file in the repository. Thank you!

**Comment by l0he1g** [comment]
> I wouldn't mind creating an R wrapper around this code, but for this, can you please add the license file in the repository. Thank you!

Thanks, jwijffels! I have added Apache License in the code.

**Comment by xiaohuiyan** [comment]
> I wouldn't mind creating an R wrapper around this code, but for this, can you please add the license file in the repository. Thank you!

Thanks, jwijffels! I have added Apache License in the code.

**Comment by jwijffels** [comment]
Where is it, can't find the license :)

**Comment by xiaohuiyan** [comment]
Sorry, the uploading takes a few of minutes. It can be found now.

**Comment by jwijffels** [comment]
Great! Many thanks!

**Comment by jwijffels** [comment]
FYI. I've made an R package wrapping the C++ code. It's currently avaiable at https://github.com/bnosac/BTM
Feel free to provide feedback before I'll push it to cran.

**Comment by jwijffels** [comment]
FYI. It's now also distributed on CRAN https://CRAN.R-project.org/package=BTM
