### ISSUE TITLE
Error in runExample.sh

### ISSUE THREAD

**Issue by kevinbsc** [xiaohuiyan/BTM#3]
I am running "runExample.sh" in Windows7 using cygwin. The following error message occurs every time I run "runExample.sh"

$ bash runExample.sh
runExample.sh: line 6: bc: command not found
=============== Index Docs =============
index file:  ../sample-data/doc_info.txt
write file:  ../output/doc_wids.txt
n(w)= 28634
write: ../output/voca.txt
=============== Topic Learning =============
runExample.sh: line 29: make: command not found
../src/btm est 20 28634  0.005 500 501 ../output/doc_wids.txt ../output/model/
runExample.sh: line 31: ../src/btm: No such file or directory
================ Infer P(z|d)===============
../src/btm inf sum_b 20 ../output/doc_wids.txt ../output/model/
runExample.sh: line 36: ../src/btm: No such file or directory
================ Topic Display =============
K:20, n(W):28634
Traceback (most recent call last):
  File "topicDisplay.py", line 53, in <module>
    pz = read_pz(pz_pt)
  File "topicDisplay.py", line 18, in read_pz
    return [float(p) for p in open(pt).readline().split()]
IOError: [Errno 2] No such file or directory: '../output/model/k20.pz'

**Comment by xiaohuiyan** [comment]
Hi @kevinbsc, bc is an arbitrary precision numeric processing language. You need to install the bc package first. The package can be found in https://cygwin.com/packages/package_list.html.
