### ISSUE TITLE
Convergence indicator?

### ISSUE THREAD

**Issue by usptact** [xiaohuiyan/BTM#6]
When learning a model, is there any indicator of convergence available or easy to compute? Currently the only information is the iteration number.

**Comment by xiaohuiyan** [comment]
Thanks for your suggestion. Typically, we training a topic model with about 500 iterations, which usually get good results. A better way is to output perplexity to illustrate the convergence more clearly. 

I'm sorry that the code has not maintained for a while after my graduation. As I found there are still so many people interest in BTM, I'm plan to develop a next version of it in few months, which will bring much improvements includes the convergence tracking.
