### ISSUE TITLE
./src/btm: No such file or directory

### ISSUE THREAD

**Issue by sruteesh** [xiaohuiyan/BTM#8]
When I run runExample.sh I am getting the following error

=============== Topic Learning =============
make: Entering directory `/home/saipavan/Desktop/BTM-master/src'
g++  -c -pipe -O3 model.cpp -o model.o 
make: g++: Command not found
make: *** [model.o] Error 127
make: Leaving directory`/home/saipavan/Desktop/BTM-master/src'
../src/btm est 20 28634 2.500 0.005 500 501 ../output/doc_wids.txt ../output/model/
runExample.sh: line 31: ../src/btm: No such file or directory

When I browsw through the src folder I couldn't find any file named btm. Please respond.

**Comment by shachi04** [comment]
src/btm is the executable created on the 'make' command. Looks like its not able to find the g++ compiler. Try to type  'g++' and run on the terminal. If you get a 'command not found' error, then the compiler is missing. You'll need to install g++ first.

**Comment by sruteesh** [comment]
Thanks @shachi04. I was able to run the program. As part of my final year
project, I wanted to use BTM for understanding topics of a user and his
followers. But to get a single output(topics of the user) BTM is taking
around 3-4 min ( I am using Ubuntu 2nd gen i5 system with 4GB RAM). This is
way too long as you can imagine the time it would take to understand the
topics of 1000 followers. Is there any way around. Any help is greatly
appreciated.
ᐧ

On Tue, Apr 12, 2016 at 2:34 AM, shachi04 notifications@github.com wrote:

> src/btm is the executable created on the 'make' command. Looks like its
> not able to find the g++ compiler. Try to type 'g++' and run on the
> terminal. If you get a 'command not found' error, then the compiler is
> missing. You'll need to install g++ first.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/xiaohuiyan/BTM/issues/8#issuecomment-208559901

## 

Regards,
Sruteesh Kumar,
5th year Undergrad,
Dept. of Engineering Design
IIT Madras,
Ph: 9043412821

**Comment by xiaohuiyan** [comment]
Hi, @sruteesh, the training time of BTM is time-consuming, but the inference of BTM is fast. You can first training BTM to learning all the topics over the whole data, and then infer each person's topics.
